<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php include '../../phpinclude/headsubsub.php'; ?>
    <meta name="description" content="How to prepare for a MUN conference.">
    <title>Preparation</title>
</head>
<body>
    <?php include '../../phpinclude/navsubsub.php'; ?>
    <div class="imagebg" style="background-image:url(../../content/images/resources.JPG)">
        <div class="imagefull" id="viewport">
            <div class="gradfull centerflex">
                <div>
                    <h1 class="animated bounceInDown" style="margin-top:0px;">Preparation</h1>
                </div>
            </div>
        </div>
        <div class="blue container-body">
            <div class="container">
                <a href="PreparationGuide.pdf" class="confbut"><h2>Printable PDF</h2></a>
                <h2>Purpose of Model United Nations</h2>
                <h3>The goal of an MUN conference is to accurately replicate the debate and diplomacy that takes place in a real United Nation's conference. In order to achieve this, we strive to follow the parliamentary procedure and structure of the UN.</h3>
                <h3>Each conference contains multiple committees, which remain separate throughout the conference. These committee each address a number of topics structured around current world issues, such as maritime piracy or HIV prevalence. The goal of each committee is to come to an agreement on how to solve the issues and to create a resolution that outlines these solutions. These resolutions will then be followed by all member nations in the future to hopefully solve the issue.</h3>
                <h3>Another goal of the United Nations is to allow all member nations to share their views and opinions in order to reach multilateral agreements that satisfy the entire world. For this reason, each nation is allowed to send a single delegate to each committee, where the delegate will represent that country's viewpoint on that committee's topics. While certain committees (such as DISEC and UNESCO) are open to all nations, others, (such as ECOSOC and the Security Council) are limited to certain nations.</h3>
                <h2>The Job of a Delegate</h2>
                <h3>As a delegate, your job is to accurately represent your country's viewpoint in your committee. It is therefore extremely important that you always stick to your country's position, even if it conflicts with your own. Your ultimate goal is to insure that any resolutions passed by your committee benefit your country. For example, if you were representing the United States in a committee addressing civilian casualties, and many nations were pushing to ban drone strikes, you would want to do everything in your power to prevent a resolution banning drone strikes. There are a variety of ways that you influence the resolutions of your committee:</h3>
                <h3>The most common way to spread your country's position is through formal speeches. Throughout the conference, you will have a variety of opportunities to speak before your committee. These include the secondary speakers list and moderated caucuses, among others (see flow of debate below for more information). Through these formal speeches, you can inform the rest of the committee of your country's position on the issue. You can be as specific or as general as you wish. No matter your experience level, we strongly encourage all delegates to make at least one formal speech during the conference.</h3>
                <h3>The second way to spread your position is through informal interactions with other delegates, most often through unmoderated caucuses. During an unmoderated caucus, the committee has a temporary recess where delegates have the opportunity to engage in one-on-one conversation regarding the topic. This is a great opportunity to begin forming solutions to the issue at hand with your allies. It is also a great opportunity to begin working on a resolution, or to speak with other delegates who are writing resolutions.</h3>
                <h3>The third and most direct way to influence the resolutions of your committee is to write your own resolution. After you have found allies who share the same position on the issue, you can use the time given during unmoderated caucuses to draft your own resolution on the topic. This resolution will outline solutions that member nations can pursue to solve the issue at hand. Of course, it is vital that any solutions that you suggest align with the position of your country. At the end of the conference, you can present your resolution to your committee, where it will be voted upon. For more information regarding the resolution writing process, see the <a href="../resolutions">resolution guideline.</a></h3>
                <h3>As discussed before, it is very important that you remain impersonal throughout the conference. Remember that you are representing your country's views, not your own. For this reason, you must always avoid using the first person during both formal and informal speech (this includes I, my, etc.) For example, if you were representing the United Kingdom, instead of saying "I believe that…," you should say "The United Kingdom believes that…" or "the delegate from the UK believes that." This applies even when you are giving non-opinionated statements, such as "the United Kingdom moves for a moderated caucus." </h3>
                <h2>Research</h2>
                <h3>Research plays an important role in the preconference preparation process. In order to keep up with debate the day of the conference, it is vital that you have a good understanding of the topic, past UN action, and your country's position. Even for shy or inexperienced delegates, this knowledge will be extremely helpful and can help give you confidence.</h3>
                <h3>The best place to begin with your research is your committee's background guide. Nearly all conferences will post extensive background guides for each committee which contain overviews of each committee topic. This will include the origin of the issue, how the issue has escalated or changed over time, the current state of the issue, and previous actions taken by the UN and nations to address the issue. All of this information is extremely useful, so we highly suggest that you fully read your committee's background guide. At the end of each topic section, you will find a series of questions to help you analyze the information discussed in the background guide and apply it to your own country. After performing additional research on your own, we suggest that you come back to these questions.</h3>
                <h3>While background guides provide a great first step in your research, the process certainly does not end here. Background guide are written in broad terms, lacking the details and specific examples that you can find through individual research. You will find a list of suggested websites at the end of your background guide to help you get started with your research.</h3>
                <h3>Therefore, it is vital that perform further research on your country. This includes finding general information, such as the location, size, major industries, and main allies of your nation, as well as finding specific evidence of your nation's position on the topic. Remember that in MUN, you are required to represent the position of your country rather than your own, so it is vital that you fully understand your country's position on each topic. We suggest that you begin by visiting the government website of your country, where you may be able to find previous legal or legislative decisions on the topic. If you have a smaller country, you may have a hard time finding evidence of your country's position. If so, try researching the positions of your closest allies and assume that your nation will take the same position. For example, while it may be hard to find Luxemburg's position on arming Syrian rebels, you can safely assume that Luxemburg will have the same position as France, since they are extremely close allies.</h3>
                <h3>As world issues are constantly evolving, it is necessary that you stay up to date on the most recent developments regarding your topic. In general, the information found on government or UN websites will be somewhat outdated, so it is important that you also refer to news sources to stay up to date. Do note that a majority of news outlets, especially partisan ones, often present biased information, so be sure to view a variety of different sources to develop a more accurate and objective view of the situation.</h3>
                <h3>After you finish your research, we highly suggest that your record and organize your findings such that you do not forget them. During the conference, it will be cumbersome so sort through you previous research material, so we suggest that you create a fact sheet that you can easily access during the conference. Here are some things you may want to include in your fact sheet:</h3>
                <h3><b>1.</b> Background: Briefly summarize the core issue in your own words.</h3>
                <h3><b>2.</b> Examples of the issue: Record the strongest examples that you found of the causes and effects of the issue. That way, you can explicitly reference these examples during your speeches to support your position and gain credibility.</h3>
                <h3><b>3.</b> Past UN action: First summarize the general approach that the UN has taken to solve this issue. This will help you make sure that your committee's resolutions do not merely repeat past UN actions. Second, provide a few exact quotes or paraphrase from important past resolutions (as well as the resolution name) so that you can explicitly quote them during formal debate.</h3>
                <h3><b>4.</b> Country Profile: Briefly answer the following questions about your country:</h3>
                <h3><b>a.</b> Where is your country located? Who are its neighbors? What sort of relationship does your country have with these neighbors?</h3>
                <h3><b>b.</b> What organizations is your country affiliated with (such as NATO, European Union, APEC, etc.)?</h3>
                <h3><b>c.</b> Who are your country's closest allies? This includes military, political, and economic allies.</h3>
                <h3><b>d.</b> What are the largest industries in your nation? Does the topic affect these industries in any way?</h3>
                <h3><b>e.</b> Does your country have any major imports or exports? If so, with whom does this trade occur?</h3>
                <h3><b>f.</b> Does your country have particularly strong animosity towards another country or group of countries? If so, what caused this animosity?</h3>
                <h3><b>5.</b> Position: Briefly summarize your country's position on the issue and their stake in the issue.</h3>
                <h3><b>6.</b> Solutions: Brainstorm a few possible solutions to the issue. This will be useful when writing resolutions.</h3>
                <h3>If you are getting stuck, the following resources are a great place to get started:</h3>
                <h3>- <a href="http://www.un.org/en/">http://www.un.org/en/</a> This is the official website for the United Nations, and is a great place to find previous UN action regarding your topic.</h3>
                <h3>- <a href="http://www.un.org/en/documents/ods">http://www.un.org/en/documents/ods</a> This is a collection of all resolutions passed by the UN.</h3>
                <h3>- <a href="https://www.cia.gov/library/publications/the-world-factbook/docs/profileguide.html">https://www.cia.gov/library/publications/the-world-factbook/docs/profileguide.html</a> This is the CIA World Factbook, which provides general information about every nation. It was created by the US government and contains relatively unbiased information. This is a great starting place to learn about your nation. </h3>
                <h2>Glossary</h2>
                <h3><b>Committee:</b> A committee is a subdivision of the United Nations, tasked with tackling a specific type of world issue. For example, the World Health Organization (WHO) focuses on medical and humanitarian issues, while the Disarmament and International Security Committee (DISEC) focuses on military issues. During the conference, each committee will run independently to address completely separate topics.</h3>
                <h3><b>Dais:</b> Each committee consists of 2 – 4 dais members who are in charge of running committee sessions. Dais members perform important tasks such as facilitating votes, choosing who can speak, approving working papers, and providing guidance to inexperienced delegates.</h3>
                <h3><b>Delegate:</b> A delegate is an individual representing a country in a committee. A delegate's job is to accurately portray the views of their nation and makes sure that the resolution passed is beneficial to their country and allies.</h3>
                <h3><b>Dilatory:</b> The term dilatory is used to describe any action that causes delay in reaching a solution. If the dais feels that a delegate's speech is inappropriate or causing delay (such as getting off topic, repeating a previously made point, or singling out a specific delegate), the dais will cut off the delegate and rule their speech dilatory.</h3>
                <h3><b>Draft Resolution:</b> Once a working paper is accepted by the dais, it becomes a draft resolution. Draft resolutions can be presented to the committee and voted on in voting bloc.</h3>
                <h3><b>Moderated Caucus:</b> Moderated caucuses are used to focus debate on a more specific topic or issue. Here, delegates raise their placards and are chosen by the dais to speak. Moderated caucuses must have a total time, a speaking time, and a dedicated topic.</h3>
                <h3><b>Operative Clause:</b> Operative clauses make up the main body of a resolution. They provide guidelines to member nations on how to solve the issue at hand.</h3>
                <h3><b>Placard:</b> A placard is a delegates name card, which contains the name of the country which that delegate represents. Delegates raise their placards when they wish to be called on by the dais and to vote on parliamentary procedure.</h3>
                <h3><b>Point of Inquiry:</b> After a speech, a delegate can raise a point of inquiry to ask the dais a question. This could include questions about procedural matter or a clarifying question pertaining to the topic at hand.</h3>
                <h3><b>Point of Order:</b> A delegate can raise a point of order if they believe parliamentary procedure has been violated.</h3>
                <h3><b>Point of Personal Privilege:</b> After a speech, a delegate can raise a point of personal privilege to ask for some sort of change such as closing the blinds or turning on the air conditioning.</h3>
                <h3><b>Perambulatory Clause:</b> Perambulatory clauses make up the first half of a resolution. Their purpose is to provide background information to set up the operative clauses.</h3>
                <h3><b>Present:</b> If a delegate registers as present, it means that they are present and retains the right to abstain during voting bloc. However, they still must vote on all procedural matters.</h3>
                <h3><b>Present and Voting:</b> If a delegate registers as present and voting, it means that they are present and must vote either yes or no during voting bloc (they cannot abstain).</h3>
                <h3><b>Primary Speakers List:</b> The primary speakers list is opened at the beginning of the first committee session. Delegates can choose to be added to the primary speakers list, were they will then be called in order to give a short speech about which topic should be addressed first. The purpose of this is to persuade other delegates to set the agenda as you best see fit.</h3>
                <h3><b>Quorum:</b> Quorum refers to the minimum number of delegates that can be present for a session to be allowed to run, which is one third in the United Nations. If quorum is not met, meaning that more than two thirds of the delegates are not present, the committee session cannot begin.</h3>
                <h3><b>Roll Call:</b> Roll is taken at the beginning of each committee session. All delegates must answer either present or present and voting. If quorum is met, the committee session will then begin.</h3>
                <h3><b>Secondary Speakers List:</b> The secondary speakers list is opened once the agenda is set and stays open until voting bloc. Here, delegates give a short speech on the topic at hand, and can speak as broadly or as specifically as they wish. This is the default type of speech.</h3>
                <h3><b>Setting the Agenda:</b> During the primary speaker's list, a delegate can move to set the agenda, where they chose the order in which the topics will be addressed. This order is then voted upon by the committee, and if it receives a simple majority, it passes and the committee enters the secondary speakers list for the first topic.</h3>
                <h3><b>Simple Majority:</b> A simple majority is required to pass all procedural matters, such as setting the agenda or entering a moderated caucus. A simple majority is reached if more than 50% of the delegates vote yes.</h3>
                <h3><b>Signatory:</b> A signatory is a supporter of a resolution who feels that the resolution should be addressed by the committee, but has not made major contributions to it. Signatories do not necessarily need to agree with the resolution, and they can vote against it during voting bloc. Sponsors should work to gain as many signatories as possible.</h3>
                <h3><b>Sponsor:</b> A sponsor is one of the main writers of a resolution who has made major contributions to it. During voting bloc, sponsors must vote yes on their resolutions. In general, there should be somewhere between 2 and 4 sponsors on a resolution.</h3>
                <h3><b>Super Majority:</b> A super majority is use in very rare instances, such as voting to vote by roll call. A super majority is reached if more than 66% of the delegates vote yes.</h3>
                <h3><b>Topic:</b> A topic is an issue that the committee will attempt to solve during the conference. Each committee has between 2 and 3 topics to choose from. When setting the agenda, delegates have the ability to choose in which order to address the topics.</h3>
                <h3><b>Unmoderated Caucus:</b> Unmoderated caucuses are used to allow for free flowing debate. Here, the delegates are given a period of recess where they can move around the room to talk with other delegates and/or work on resolutions.</h3>
                <h3><b>Voting Bloc:</b> After at least one draft resolution is accepted by the dais, delegates can move to enter voting bloc. Once in voting bloc, delegates chose in which order to vote on the approved draft resolutions, and then commence voting. The first draft resolution with a simple majority passes and becomes a full resolution. Certain committees may allow more than one resolution to be passed per topic.</h3>
                <h3><b>Working paper:</b> As delegates begin writing a resolution, it is referred to as a working paper. Only once the dais approves a working paper does it become a draft resolution. </h3>
            </div>
            </div>
</div>
    <?php include '../../phpinclude/footer.php'; ?>
</body>
</html>